### PR TITLE
Fixed linting errors

### PR DESCRIPTION
**Pull request by asaravindkumar**
## What kind of change does this PR introduce?

Bug fix - fixed linting issues

## What is the current behavior?

Please link any relevant issues here. #3 

## What is the new behavior?

Improved code quality

## Additional context

Add any other context or screenshots.

### CODE REVIEW

**Comment by phamhieu** [comment]
Hi @asaravindkumar, thanks for your contribution to postgrest-dart library.

I checked your fix. There are still many lint errors on `builder.dart` file. Could you take a look? 
You can run `dartanalyzer lib/postgrest.dart` to see all errors

Screenshot 2020-10-02 at 6 07 35 AM

**Comment by asaravindkumar** [comment]
@phamhieu sure I just checked and updated (including test files) Now only the following is pending. rest is all fixed
Screen Shot 2020-10-02 at 7 41 13 AM

**Comment by phamhieu** [comment]
There are only 6 errors left. @asaravindkumar good job! you're nearly there.

Screenshot 2020-10-02 at 2 47 51 PM

**Comment by asaravindkumar** [comment]
@phamhieu  How about now? The remaining 6 are fixed.

**Comment by phamhieu** [comment]
Nice work @asaravindkumar. Thanks you.

**Review by phamhieu — APPROVED** [review]

**Pull request merged**
