### PR TITLE
feat: isolates for heavy computation

### PR DESCRIPTION
**Pull request by Vinzent03**
I copied the `compute` function from flutter foundation and removed useless code.

Shall we close the following issues, or wait unitl the other packages use isolates too? Is that even necessary?
 supabase-community/supabase-flutter/issues/150
supabase-community/supabase-flutter/issues/77

### CODE REVIEW

**Comment by bdlukaa** [comment]
Decode should be taken into consideration

- https://github.com/supabase-community/postgrest-dart/blob/master/lib/src/postgrest_builder.dart#L194
- https://github.com/supabase-community/postgrest-dart/blob/master/lib/src/postgrest_builder.dart#L221

**Comment by Vinzent03** [comment]
Thanks for quick check. I know, but I'm still in testing, because I need the docker image here on GitHub actions. In addition, I don't get the analyzer warning locally.

**Comment by bdlukaa** [comment]
>  In addition, I don't get the analyzer warning locally.

Try to restart your IDE

**Comment by Vinzent03** [comment]
Already tried that 😉. I even checked via raw `dart analyze`. Fixed it now by upgrading dart to `2.18` via beta channel.

**Review by bdlukaa — APPROVED** [review]

**Review by dshukertjr — APPROVED** [review]
@Vinzent03 Wow, this is so beautiful!

@bdlukaa I don't think there is going to be heavy json parsing on other packages, so I don't think we need to add function to use isolates on other packages, therefore the linked issues are good to be closed, but would you agree?

**Pull request merged**
